### ISSUE TITLE
[BUG] Returned value from MessageReceived (IPlugin) not sending message to the controller 

### ISSUE THREAD

**Issue by AlFaMoDz** [ivao-xa/TrainingServer#10]
**Affected Interface**
IPlugin

**Describe the Bug**
Value returned in MessageReceived() (IPlugin) isnt sent by PM to the controller

**Expected Behavior**
Send a private message to the controller the returned value

**Environment (please complete the following information)**
 - Server OS/Architecture W11/Debian 11
 - Server Version 1.0.5

**Comment by wessupermare** [comment]
This is a bug in the core server, I think. I'll take a look into it today and get back to you on it.

**Comment by wessupermare** [comment]
Should be closed by #16. Let me know if it doesn't work still and I'll re-open the issue.
