### ISSUE TITLE
[REQUEST] Pause aircraft mid-air

### ISSUE THREAD

**Issue by NikoDervaric** [ivao-xa/TrainingServer#7]
**Server**
I would to have the ability to pause all aircraft mid-flight in order to discuss situations on the fly and resolve issues with trainees/other trainers. 

**Describe the solution you'd like**
Send message to server (123.450) with message `PAUSE`, which would stop all aircraft. `UNPAUSE` would resume all flights. 

**Additional context**
None

**Comment by wessupermare** [comment]
I can take this one!
